"""Image preprocessing settings (common preprocess only)."""

from pathlib import Path

import settings as S

ROOT = S.ROOT

GALLERY_RAW_DIR = S.GALLERY_RAW_DIR
PATIENTS_RAW_DIR = S.PATIENTS_RAW_DIR
GALLERY_PREPROCESSED_DIR = S.GALLERY_PREPROCESSED_DIR
PATIENTS_PREPROCESSED_DIR = S.PATIENTS_PREPROCESSED_DIR

IMAGE_EXTENSIONS = S.IMAGE_EXTENSIONS

LETTERBOX_SIZE = S.LETTERBOX_SIZE
LETTERBOX_PAD_COLOR = S.LETTERBOX_PAD_COLOR
CLAHE_CLIP_LIMIT = S.CLAHE_CLIP_LIMIT
CLAHE_TILE_GRID = S.CLAHE_TILE_GRID
DENOISE_D = S.DENOISE_D
DENOISE_SIGMA_COLOR = S.DENOISE_SIGMA_COLOR
DENOISE_SIGMA_SPACE = S.DENOISE_SIGMA_SPACE
