import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F4F6F8" },
  container: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#F4F6F8",
  },
  scrollContent: { paddingBottom: 120 },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5EAF2",
  },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  backButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF3F8",
  },
  backButtonText: {
    fontSize: 24,
    lineHeight: 24,
    color: "#274062",
    fontWeight: "700",
  },
  logoText: { fontSize: 24, fontWeight: "800", color: "#0B4EA2" },
  iconText: { fontSize: 20 },
  section: { marginTop: 12, paddingHorizontal: 16 },
  searchWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C9D4E5",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchText: { color: "#8A97AB", fontSize: 14 },
  floorLabel: { fontSize: 12, fontWeight: "700", color: "#2A5EA2", letterSpacing: 1.2 },
  roomTitle: { fontSize: 42, fontWeight: "800", color: "#1E3554" },
  occupancyChip: {
    borderRadius: 14,
    backgroundColor: "#EEF2F7",
    paddingHorizontal: 12,
    paddingVertical: 4,
    color: "#5A6C86",
    fontWeight: "700",
  },
  patientGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginTop: 10 },
  patientCard: {
    width: "48.5%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#C6D4E6",
    backgroundColor: "#FFFFFF",
    padding: 12,
    marginBottom: 10,
    alignItems: "center",
  },
  patientCardSelected: {
    borderWidth: 3,
    borderColor: "#0B4EA2",
  },
  avatarCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 6,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  avatarInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 36, fontWeight: "700" },
  patientName: { fontSize: 17, fontWeight: "800", color: "#273A55" },
  patientStatus: { fontSize: 13, marginTop: 3, color: "#4B5D76", fontWeight: "600" },
  dangerText: { color: "#CC4957" },
  mealCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#C7D7ED",
    backgroundColor: "#FFFFFF",
    padding: 14,
  },
  mealHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  mealTitle: { fontSize: 38, fontWeight: "800", color: "#0B4EA2" },
  tabs: { flexDirection: "row", backgroundColor: "#ECECEC", borderRadius: 18, padding: 3 },
  tab: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14 },
  tabActive: { backgroundColor: "#FFFFFF" },
  tabText: { color: "#6B7280", fontSize: 12, fontWeight: "600" },
  tabTextActive: { color: "#0B4EA2", fontWeight: "800" },
  mealBody: { flexDirection: "row", marginTop: 10, gap: 12 },
  mealThumb: {
    width: 96,
    height: 96,
    borderRadius: 18,
    backgroundColor: "#D7C19B",
    alignItems: "center",
    justifyContent: "center",
  },
  mealMain: { fontSize: 30, fontWeight: "800", color: "#0B4EA2" },
  mealSub: { fontSize: 14, color: "#334155", marginTop: 4 },
  doneBadge: {
    marginTop: 8,
    alignSelf: "flex-start",
    backgroundColor: "#DCEBFF",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  doneText: { color: "#0B4EA2", fontWeight: "700", fontSize: 12 },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 86,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#D8E1EE",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 8,
  },
  bottomItem: { alignItems: "center" },
  bottomLabel: { marginTop: 4, fontSize: 13, color: "#6B7280", fontWeight: "700" },
});
