import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F6F8",
  },
  container: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#F4F6F8",
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5EAF2",
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  backButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF3F8",
  },
  backButtonText: {
    fontSize: 24,
    lineHeight: 24,
    color: "#274062",
    fontWeight: "700",
  },
  logoText: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0B4EA2",
  },
  iconText: {
    fontSize: 20,
  },
  patientStrip: {
    marginTop: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E1E6EF",
    backgroundColor: "#F8FAFD",
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  patientName: {
    fontSize: 28,
    fontWeight: "700",
    color: "#243B58",
  },
  patientMeta: {
    marginTop: 2,
    fontSize: 14,
    color: "#73839A",
  },
  section: {
    marginTop: 12,
    paddingHorizontal: 12,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1F3552",
    marginBottom: 8,
  },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D9E0EB",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  row: {
    borderBottomWidth: 1,
    borderBottomColor: "#EDF1F6",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2B3F5C",
  },
  rowLeft: {
    flex: 1,
    paddingRight: 10,
  },
  rowSubWarn: {
    marginTop: 3,
    fontSize: 11,
    color: "#C13E48",
    fontWeight: "700",
  },
  stateWrap: {
    flexDirection: "row",
    gap: 6,
  },
  stateBtn: {
    minWidth: 52,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D6DDE8",
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  stateBtnActive: {
    backgroundColor: "#0B4EA2",
    borderColor: "#0B4EA2",
  },
  stateBtnDanger: {
    backgroundColor: "#FCEFF1",
    borderColor: "#D66B78",
  },
  stateText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#66768E",
  },
  stateTextActive: {
    color: "#fff",
  },
  stateTextDanger: {
    color: "#B64754",
  },
  memoInput: {
    margin: 10,
    borderWidth: 1,
    borderColor: "#E1E6EF",
    borderRadius: 8,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: "#334155",
    backgroundColor: "#FAFCFF",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 84,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#D8E1EE",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 8,
  },
  bottomItem: {
    alignItems: "center",
  },
  bottomLabel: {
    marginTop: 4,
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "700",
  },
});
