import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F6F8",
  },
  container: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#F4F6F8",
  },
  scrollContent: {
    paddingBottom: 120,
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoText: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0B4EA2",
  },
  headerIcons: {
    flexDirection: "row",
    gap: 14,
  },
  iconText: {
    fontSize: 20,
  },
  section: {
    paddingHorizontal: 16,
    marginTop: 14,
  },
  patientSelect: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    paddingVertical: 10,
    alignItems: "center",
  },
  patientSelectText: {
    fontWeight: "700",
    color: "#274062",
  },
  patientPickerList: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  patientPickerItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2F7",
  },
  patientPickerItemText: {
    color: "#334155",
    fontWeight: "600",
    fontSize: 13,
  },
  card: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    padding: 14,
  },
  cardTitle: {
    fontSize: 29,
    fontWeight: "800",
    color: "#223A5B",
    marginBottom: 8,
  },
  dayRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  dayCell: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#F0F3F8",
    alignItems: "center",
    justifyContent: "center",
  },
  dayCellActive: {
    borderWidth: 2,
    borderColor: "#4A6FAE",
    backgroundColor: "#FFFFFF",
  },
  dayText: {
    color: "#6B7280",
    fontWeight: "600",
    fontSize: 12,
  },
  legendItem: {
    fontSize: 12,
    color: "#475569",
    marginTop: 6,
  },
  sectionTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#1F2F47",
    marginBottom: 8,
  },
  importantCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DFE5EF",
    backgroundColor: "#FFFFFF",
    padding: 12,
    marginBottom: 10,
  },
  importantTitle: {
    fontSize: 25,
    fontWeight: "700",
    color: "#26384F",
  },
  importantDesc: {
    fontSize: 17,
    color: "#64748B",
    marginTop: 2,
  },
  quickWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  quickCard: {
    width: "31%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D4DCE8",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    paddingVertical: 14,
    gap: 6,
  },
  quickLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
  },
  mealCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    padding: 14,
  },
  mealTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#1F2F47",
    marginBottom: 8,
  },
  noticeTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#1F2F47",
  },
  noticeCard: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  noticeMain: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1F2F47",
  },
  noticeDate: {
    marginTop: 4,
    fontSize: 17,
    color: "#7C8CA4",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 84,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#D8E1EE",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 8,
  },
  bottomItem: {
    alignItems: "center",
  },
  bottomLabel: {
    marginTop: 4,
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "700",
  },
  bottomLabelActive: {
    color: "#0B4EA2",
  },
});
