spring:
  application:
    name: ddasum
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ddasum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: none
>>>>>>> 1039d55f3b99df2abaf1450d9e2f351e3b91d9bf
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
<<<<<<< HEAD
=======

server:
  port: 8081
>>>>>>> 1039d55f3b99df2abaf1450d9e2f351e3b91d9bf
